name: Profil Submission
description: Ein neues Entwickler-Profil für das Repository vorschlagen.
title: "[Profil Submission] <dein Name>"
body:
  - type: input
    id: username
    attributes:
      label: GitHub Username
      description: Dein GitHub-Benutzername
      placeholder: z.B. maxmustermann
    validations:
      required: true
  - type: input
    id: nexusmods
    attributes:
      label: Nexus Mods Name (optional)
      description: Dein NexusMods-Account
  - type: input
    id: curseforge
    attributes:
      label: CurseForge Name (optional)
      description: Dein CurseForge-Account
  - type: textarea
    id: bio
    attributes:
      label: Kurz-Bio/Über dich (optional)
